export const ROUTES = {
  MINDFUL_MENTOR: "/mindful-mentor-web",
  LOGIN: "/login",
  WEB: "/web",
  DASHBOARD: "/dashboard",
  HOME: "/home",
  ITEM_TYPE : "/item-type",
  PROFILE: "/profile",
  CALENDAR: "/calendar",
  COUNSELOR: "/counselor",
  APPOINTMENTS: "/appointments",
  STUDENTS: "/students",
  CHATS: "/chats",
  ACCOUNT_REQUEST: "/accountRequest",
  JOURNAL: "/journal",
};
